extremeshelf = [
  { "name": "Extreme Physics 9 - 10", "id": "e1" },
  { "name": "Extreme Chemistry 9 - 10", "id": "e2" },
  { "name": "Extreme Biology 9 - 10", "id": "e3" },
  { "name": "Extreme Mathematics 9 - 10", "id": "e4" },
  { "name": "Extreme English 9 - 10", "id": "e5" },
  { "name": "Master of Thinking", "id": "e6" },
  { "name": "Think Smarter", "id": "e7" },
  { "name": "Oxford English Grammar", "id": "e8" },
  { "name": "Ancient and Modern Physics", "id": "e9" },
  { "name": "Biology", "id": "e10" },
  { "name": "Geography and Play", "id": "e11" },
  { "name": "Myths and Marvels Astronomy", "id": "e12" },
  { "name": "History of Astronomy", "id": "e14" },
  { "name": "Code Three", "id": "e15" },
  { "name": "The Code of Honor", "id": "e16" },
  { "name": "Advanced Language Practice", "id": "e17" },
  { "name": "English Grammar in Use", "id": "e18" },
  { "name": "English Grammar in Use 2", "id": "e19" },
  { "name": "Advanced English Conversation", "id": "e20" },
  { "name": "Spoken English", "id": "e21" },
  { "name": "Advanced Worldwide 2", "id": "e22" },
  { "name": "Advanced Worldwide 1", "id": "e23" },
  { "name": "Extreme Physics Grade 11 - 12", "id": "e25" },
  { "name": "Physics Problems", "id": "e27" },
  { "name": "Data Science", "id": "e28" },
  { "name": "Basic WiFi Hacking", "id": "e29" },
  { "name": "Code 2", "id": "e30" },
  { "name": "Code Breaker", "id": "e31" },
  
  { "name": "Plasma Physics", "id": "e32" },
  { "name": "Cloud Physics", "id": "e33" },
  { "name": "Manual Physics", "id": "e34" },
  { "name": "Algebra", "id": "e35" },
  { "name": "Financial Mathematics", "id": "e36" },
  { "name": "Applied Mathematics", "id": "e37" },
  { "name": "Mathematics for 11", "id": "e38" },
  { "name": "Pure Mathematics", "id": "e39" },
  { "name": "Mathematics", "id": "e40" },
  { "name": "The Alchemist", "id": "e41" },
  { "name": "Rich Dad Poor Dad", "id": "e42" },
  { "name": "Love Under Construction", "id": "e43" },
  { "name": "The Alchemist", "id": "e44" }
]